-- AlterTable
ALTER TABLE "Module" ADD COLUMN     "backMountingType" TEXT,
ADD COLUMN     "grooveDepth" DOUBLE PRECISION,
ADD COLUMN     "rearGap" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "ModuleTemplate" ADD COLUMN     "backMountingType" TEXT NOT NULL DEFAULT 'NAILED',
ADD COLUMN     "grooveDepth" DOUBLE PRECISION NOT NULL DEFAULT 9,
ADD COLUMN     "rearGap" DOUBLE PRECISION NOT NULL DEFAULT 18;

-- AlterTable
ALTER TABLE "Project" ADD COLUMN     "backMountingType" TEXT NOT NULL DEFAULT 'NAILED',
ADD COLUMN     "grooveDepth" DOUBLE PRECISION NOT NULL DEFAULT 9,
ADD COLUMN     "rearGap" DOUBLE PRECISION NOT NULL DEFAULT 18;
